### ISSUE TITLE
3D heatmap

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Makie.jl#1004]
Would it be too difficult to add a 3D heatmap like the following examples?

- https://i.stack.imgur.com/EQVaJ.jpg

- https://www.gibboncode.org/html/HELP_im2patch_02.jpg

**Comment by ffreyer** [comment]
This probably works better with CairoMakie, because CairoMakie sorts all faces by average z-value and GLMakie doesn't.
```
box = Rect3D(Point3f0(-0.4999), Point3f0(0.9998))
pos = [Point3f0(i,j,k) for i in 1:10 for j in 1:10 for k in 1:10]
cs = [RGBAf0(rand(RGBf0), 0.3) for _ in pos]
fig, as, p = meshscatter(pos, marker=box, markersize=1f0, color=cs)
```
You may also want to set `transparency = true` for GLMakie and `faceculling = -2.0` for CairoMakie. The latter sets a threshold for how "camera facing" normals have to be to not be discarded. With -2 all should be kept.

## GLMakie
![GLMakie](https://user-images.githubusercontent.com/10947937/120071500-06646b00-c090-11eb-96ab-dad9f6966e29.png)
## CairoMakie
![CairoMakie](https://user-images.githubusercontent.com/10947937/120071501-07959800-c090-11eb-8502-116b59b5099e.png)

**Comment by juliohm** [comment]
That is exactly what I needed! So this is not considered a type of `volume` plot as well? I was looking into an option in `volume` for that but couldn't find it. Now I realize that it is a plot of a couple of little cubes.

**Comment by juliohm** [comment]
I think a more general issue is if we could merge heatmap, image and volume into a single name with different options?

**Comment by ffreyer** [comment]
Volume does very different things in the shaders. I think some of (maybe even all?) the volume algorithms throw cubes into places, but they don't do it on a grid and they try to hide it.

**Comment by juliohm** [comment]
Agree, the volume is probably off compared to the other recipes, but I still think that Makie could provide a more unified approach to heatmap, image in 2D and 3D.

**Comment by juliohm** [comment]
Will mark the issue as solved because the feature is somehow there, just the API that is missing.
