### ISSUE TITLE
Problems with LaTeX strings

### ISSUE THREAD

**Issue by fbanning** [JuliaPlots/Makie.jl#1131]
First of all, thank you very much for the LaTeX string support introduced in v0.15! :)
I've currently found two problems with it which I'd like to report.

1. Trying to concatenate strings for tick labels fails 

```julia
xticks = ([0.0, 1.0, 2.0, 3.0], 
            [L"a = 0", # regular LaTeXString works fine
            "b = " * "1", # concatenating two regular strings works fine
            "c = " * L"2", # concatenating regular string & LaTeXString causes all latex string rendering for ticks to break
            L"d = " * L"3"]), # concatenating two LaTeXStrings causes all latex string rendering for ticks to break
```

It would be great if we could use multiple types of strings together. This seems to be due to the fact that the result is always the supertype `String` and not the more specific `LaTeXString`.

```julia
julia> typeof(L"c = 2")
LaTeXStrings.LaTeXString

julia> typeof("c = " * L"2")
String
```

2. Line breaks don't work and cause parsing errors

```julia
xticks = ([0.0], [L"a = \\0"])
```

This would be awesome to have more formatting options.

**Comment by fbanning** [comment]
3. Inserting regular text causes parsing errors

```julia
xticks = ([0.0], [L"a = \text{INPUT} 0"])
```

Would be cool if this would allow to "inject" regular strings into LaTeXStrings.

4. Forced spaces in equations cause parsing errors

```julia
xticks = ([0.0], [L"a \; = \; 0"])
```

This would allow for more formatting options.

**Comment by SimonDanisch** [comment]
I'm not sure if I understand the problem fully, but these look like feature requests for: https://github.com/stevengj/LaTeXStrings.jl

**Comment by fbanning** [comment]
I think you're right, most of them should be mentioned over there.

One thing that's likely a suggestion for Makie would be that the following 

```julia
xticks = ([0.0, 1.0], ["a = 0", L"b = 1"]),
```

causes both tick labels to be displayed as regular strings, i.e. the LaTeXString is just displayed as `$b = 1$` instead of being rendered by the engine.  
Maybe it's possible to render the ticks one by one so that they can be treated separately?

**Comment by jkrumbiegel** [comment]
The last three things are MathTeXEngine feature requests. The example with the two different types needs a specific routine handling multiple different AbstractStrings in one text plot, that could be a bit more difficult than it sounds due to the special requirement of latexstrings that there needs to be a linesegments plot for sqrt and frac lines.

**Comment by SimonDanisch** [comment]
Cant we just promote `([0.0, 1.0], ["a = 0", L"b = 1"])` to   `([0.0, 1.0], [L"a = 0", L"b = 1"])` ( i dont know the escaping by hard, but I guess one should be able to render a normal string in a latex string

**Comment by fbanning** [comment]
> Cant we just promote

This would be a workaround to force math rendering but if a user deliberately wants to combine regularly rendered strings and MathTeXEngine rendered strings, this would get in the way.

**Comment by SimonDanisch** [comment]
I mean my point was, that you can render regular strings as latex strings, no? Am I overestimating the escaping powers for Latex strings?

**Comment by ghralima** [comment]
I may be wrong, but it seem MathTexEngine.jl can't yet render basic fonts (\mathrm{something}) nor spaces (\, \; \: etc) in LaTeX, otherwise it would be possible to use LaTeXStrings to replace strings. Also, it can't render accent symbols like \vec{a} yet. Well, at least that's what the MathTexEngine.jl says in its current github description.

**Comment by fbanning** [comment]
Yes, I also checked for that, @ghralima. It definitely seems like MathTexEngine.jl needs a bit more work to support usual commands like spaces and text parts. Once that's implemented, we can simply use those tex commands to get what I would like to achieve (mixed formatting of standard strings and latex strings). Once this is done, I suppose promoting all regular strings to tex strings would solve the aforementioned problem with the tex rendering being omitted.

**Comment by Kolaru** [comment]
I reported the issues that goes to MathTeXEngine to keep track of everything.

> Line breaks don't work and cause parsing errors

This will ignore text alignment at first, because MathTeXEngine currently has no mechanism to deal with text alignment by itself. For single line text this call always be dealt with by the backend so it is not a problem, for multiple lines some work will maybe be needed from the Makie side too.

> Inserting regular text causes parsing errors

Once #1160 is finished, it will be accessible using `$` e.g. `L"$x = 2$ or sometimes $x = 42$"`.

Supporting other font commands should be possible in the future too (e.g. `\mathrm`).
