### ISSUE TITLE
Docstring of `heatmap` must state its configs / keyword arguments

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#1137]
From here: http://makie.juliaplots.org/stable/plotting_functions/heatmap.html#MakieCore.heatmap  there is really no info, e.g. how to choose colormap, how to set color range.

**Comment by LoganLieou** [comment]
I can help with this maybe (I am very noob).

I assume the link to this problem is [here](https://makie.juliaplots.org/stable/examples/plotting_functions/heatmap/index.html) as the link in the post is dead.

pretty sure you can set color map like `heatmap(x, y, colormap=:some_scheme)` and information on colors is in the docs [here](https://makie.juliaplots.org/stable/documentation/colors/index.html#colors), so it shouldn't be that hard to add information on how to choose colormap in the docstring right?
