### ISSUE TITLE
Request: add scene to Textbox elements? (For right-clicking on Textbox, for example)

### ISSUE THREAD

**Issue by larsmolstad** [JuliaPlots/Makie.jl#1233]
Adding the line 
`    decorations[:scene] = scene
`
at line 28 in textbox.jl 
allows something to happen when we right-click on a textbox:

    using GLMakie
    fig = Figure()
    a = Textbox(fig, stored_string="hi")
    fig[1,1] = a

    mouseevent = addmouseevents!(a.elements[:scene])
    onmouserightdown(mouseevent) do x
        println("hello!")
        return Consume(false)
    end

Are there better ways?

**Comment by larsmolstad** [comment]
I guess this is the way

    using GLMakie
    fig = Figure()
    a = Textbox(fig, stored_string="hi")
    fig[1,1] = a
    mouseevent = addmouseevents!(fig.scene, a.layoutobservables.computedbbox)
    onmouserightdown(mouseevent) do x
        println("hello!")
        return Consume(false)
    end

**Comment by ffreyer** [comment]
It doesn't actually matter which scene you use for scene.events. I played around with that and it just ended up being to slow. `addmouseevents!(scene)` is a bit different here because it tries to restrict events to relevant areas. In this case it would discard events outside the scene. If you also pass a bounding box or plots it would restrict events to those inside the boundingbox or hovering the given plots. So in your second version it's irrelevant what scene you pass since you're restricting events with the boundingbox of the layoutable.

You may still face some issues with event priority. As it currently works `addmouseevents!()` has a priority for processing `scene.events` and an internal priority that applies to the on-x functions. If you want to make sure that your mouse events run first you should use a higher priority, i.e. `addmouseevents!(..., priority = 2)` in this case.

**Comment by larsmolstad** [comment]
Thanks! I didn't know about the priority keyword.
