### ISSUE TITLE
CairoMakie rotated heatmap does not match GLMakie

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Makie.jl#1298]
On the left is the CairoMakie output, on the right is GLMakie
![image](https://user-images.githubusercontent.com/581043/132398085-dd479ff2-7e2e-4d2f-8bc6-894a19d037ce.png)

The code

```julia
using Makie: Makie, RGBA
using GLMakie: GLMakie
using CairoMakie: CairoMakie

GLMakie.activate!()

fig = Makie.Figure()
ax = Makie.Axis(fig[1, 1])
ax.title = "title"

lsgrid = Makie.labelslidergrid!(
    fig,
    ["x", "y", "z", "deg"],
    [0:0.01:1, 0:0.01:1, 0:0.01:1, 0:1.0:360];
)
Makie.set_close_to!(lsgrid.sliders[3], 1.0) # lsgrid.sliders[3].value[] = 1.0
fig[2, 1] = lsgrid.layout

sliderobservables = [s.value for s in lsgrid.sliders]
quat = Makie.lift(sliderobservables...) do (arg...)
    (x, y, z, deg) = arg
    Makie.qrotation(Makie.SVector(x, y, z), deg2rad(deg))
end

ax.autolimitaspect = 1
# Makie.hidespines!(ax)
# Makie.hidedecorations!(ax) # remove ticks and tick labels
Makie.heatmap!(ax, rand(Bool, 10, 10); colormap=[RGBA(0, 0, 0, 0), RGBA(0, 0, 0, 1)])

Makie.on(quat) do q
    Makie.rotate!(fig.scene.children[1], q)
end

display(fig)

function save_pdf(fig)
    CairoMakie.activate!()
    Makie.save("/tmp/out.pdf", fig)
    GLMakie.activate!()
end

```

```
  [13f3f980] CairoMakie v0.6.5
  [e9467ef8] GLMakie v0.4.6
```

**Comment by ffreyer** [comment]
The issue with this is that the model matrix (which gets build from transformations like rotate, scale and translate) is applied to the rectangle positions but not the rectangles themselves. 
https://github.com/JuliaPlots/Makie.jl/blob/26bc35b85bd8077e6b194ff170fa74984a8de3a6/CairoMakie/src/primitives.jl#L566
Rotation and scale should be applied again to each rectangle. There might be a matrix transformation we can set in Cairo to do that. That matrix could probably just be `model[Vec(1, 2), Vec(1, 2)]`. (Because the 1:3, 1:3 section is rotation + scale.) If there is a `rectangle(p1, p2, p3, p4)` that could also work.
https://github.com/JuliaPlots/Makie.jl/blob/26bc35b85bd8077e6b194ff170fa74984a8de3a6/CairoMakie/src/primitives.jl#L602
