### ISSUE TITLE
Blurry menus / scaling issues using multiple monitors

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaPlots/Makie.jl#1470]
I'm working on a 13" 2018 MacBook Pro having a WQHD monitor connected via HDMI (over a USB dock). When I try the [menu example](https://makie.juliaplots.org/stable/examples/layoutables/menu/), the menu looks very blurry on the external monitor:

![monitor](https://user-images.githubusercontent.com/8181318/143238098-2a832347-1a99-4199-a4cc-d575c00fe747.png)

When I move the window to the laptop's screen, the menus look much smaller and therefore sharper as well:

![macbook](https://user-images.githubusercontent.com/8181318/143238108-86bebc97-96dd-47fc-8b64-8b1432b24f6c.png)

#1186 is also visible when opening the upper menu.

**Comment by jkrumbiegel** [comment]
GLMakie doesn't have resolution scaling yet, so there's no hidpi support per se. That's why everything is small on a hidpi monitor. Also, GLMakie text is not the sharpest to begin with because it doesn't use hinting, so some fuzzy fonts are to be expected currently. At least you can always export with CairoMakie for higher quality.

**Comment by ffreyer** [comment]
I wonder what's actually causing GLMakie fonts to be blurry. It's not like large text looks blurry. Maybe we need to generate lower resolution glyphs and use them as mipmaps?

**Comment by SimonDanisch** [comment]
>Maybe we need to generate lower resolution glyphs and use them as mipmaps?

Yeah, that's a very good question, they should look somewhat crisp regardless of resolution - of course high-dpi will make fuzziness less obvious though... 
But, I've been noticing that for a while that it can look worse than it should, but it's somewhat hard to reproduce... I'm guessing, some pixel scaling values aren't set correctly

**Comment by ffreyer** [comment]
Ok I tried a few things. 

I tried switching to 16x16 glyph resolution by explicitly running https://github.com/JuliaPlots/Makie.jl/blob/2faa3d75733689f2d3e802b1f623d0f90343005a/src/utilities/texture_atlas.jl#L27-L29 with appropriate values.

I tried rounding positions in https://github.com/JuliaPlots/Makie.jl/blob/2faa3d75733689f2d3e802b1f623d0f90343005a/GLMakie/src/drawing_primitives.jl#L297-L299

And I tried rounding in the vertex shader here https://github.com/JuliaPlots/Makie.jl/blob/2faa3d75733689f2d3e802b1f623d0f90343005a/GLMakie/assets/shader/sprites.vert#L119

![Screenshot from 2021-11-29 18-22-32](https://user-images.githubusercontent.com/10947937/143914990-bfec5c60-240c-4be9-a9d6-2ee415b6fbb6.png)

Seems like pixel alignment is the main problem. Native (ticks use 16px fontsize by default) and high resolution glyphs look the same to me. Same with in-shader rounding vs rounding beforehand. Also interesting that libre office is so colorful, maybe that's due to dark mode?

**Comment by ffreyer** [comment]
I tried to make a pr to switch to pixel-aligned text rendering (https://github.com/JuliaPlots/Makie.jl/tree/ff/text) but it's not much of an improvement. Some glyphs look better, some worse, most just fuzzy somewhere else. So I tried a few different alignments (i.e. aligning vclip, it's constituents, or shifting by the antialiasing radius) and eventually I tried generating the texture atlas at a different resolution again. Turns out I didn't do that right. This is what 16 vs 64, floating vs pixel aligned looks like:

![Screenshot from 2021-11-30 15-24-02](https://user-images.githubusercontent.com/10947937/144067938-e1f924a1-6410-44a9-9fc1-2267d0880b8c.png)

So texture resolution does matter. Here's the normal resolution plot with 

## 16x16 glyphs (pixel aligned)
![16_pixel](https://user-images.githubusercontent.com/10947937/144068239-87fa25ff-cc38-46c3-90d9-ffcd5f4bd255.png)

Note that the axis ticks have `textsize = 16`, matching the glyph size in the texture atlas, but the text plotted into the axis has `textsize = 20`. Here's the result with 

## 20x20 glyphs (pixel aligned)

![20_pixel](https://user-images.githubusercontent.com/10947937/144068886-3c35e4ef-6f95-401a-8e37-a6fd6032851c.png)

Comparing 16x16 and 20x20 I'd say things look best when the glyph resolution matches the textsize and downscaling is better than upscaling. Both can introduce some artifacts though. I still wouldn't say pixel aligned is strictly better... Maybe a better on average?

For reference here are glyph resolutions 16x16, 20x20, 60x60, 64x64 with and without pixel alignment. 
[text.zip](https://github.com/JuliaPlots/Makie.jl/files/7626760/text.zip)
