### ISSUE TITLE
[FR] Plotting text in "axis coordinates"

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#1472]
Hi, 
MWE:
![image](https://user-images.githubusercontent.com/19669089/143241952-08bec44f-cd76-489c-87ba-a4b8dd8e932b.png)

In the bottom left corner of each axis I want to plot "s = ..." where s is the slope of the red line. It becomes unpleasant to specify the location of this text in data coordinates. I would like to specify it in "axis coordinates".

This means: I give location = (0.1, 0.1) and this plots the text in the 10% x and 10%y location of the axis. Does this make sense? In PyPlot I do this by providing a transformation, not sure if it is possible in makie. If not, consider this a feature request instead of docs. If it is possible, then please add this info here: https://makie.juliaplots.org/stable/examples/plotting_functions/text/index.html or just tell me so I do the PR.

**Comment by jkrumbiegel** [comment]
We currently don't have this, no. For `vlines!` etc I do this manually by lifting off the limits observable, you could do the same. I sometimes envy matplotlib for their transform system, because it's so flexible. I'm not sure if we should try to emulate something like it as well, or if it makes sense in the overall architecture.

For your specific issue, you could just use `Label`s that you put in the same cells as the axes, with `halign = :left` and `valign = :bottom` as well as tellheight/width false.

**Comment by Datseris** [comment]
Thanks, the Label solution is okayish, but certainly not perfect:
![image](https://user-images.githubusercontent.com/19669089/143244207-016bab1d-efba-4391-b158-02b1ca3257a5.png)

I need to pad my text with spaces for it to be clear. (and also it is very useful to be able to specify with more freedom axis proportions). 

So I rename this to [FR] and let's see how it is best implemented in the future. If I had more time I would also lift the axis observable, but as this is "normal science work", I need to focus on getting the slope there and thus writing as little makie code as possible!

**Comment by jkrumbiegel** [comment]
`Label` also has a `padding` keyword, so you could do `padding = (5, 0, 5, 0)` for example (left, right, bottom, top).
Or `halign = 0.1` etc would also work if you'd rather have it relative to axis size.
