### ISSUE TITLE
unwanted overexposed colors with the new transparency 

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/Makie.jl#1505]
Doing the following:

```
fig = Figure(resolution = (1200, 1200))
ax = Axis3(fig[1, 1]; aspect = :data, perspectiveness = 0.5)
for i in range(-1, 1, length = 400)
    heatmap!(ax, range(-1, 1, length = 100), range(-1, 1, length = 100), rand(100,100);
        transformation = (:yz, i), transparency = true, shading = false)
end
fig
```
outputs: 
<img width="567" alt="Screenshot 2021-12-09 at 21 07 35" src="https://user-images.githubusercontent.com/19525261/145468135-74a1aca6-f766-4aaf-b74f-47ae3186fccb.png">

where the corner has a really bright contrast light (overexposed). Which is noticeable when adding more and more planes.  Probably is not related to `shading` but to how the new transparencies are being deal with. Recent issue https://github.com/JuliaPlots/Makie.jl/pull/1418
This is noticeable specially along the edges.

EDIT: 

Oh!. This just happens with `Axis3` !
Doing it like follows with `LScene` works ok!

```
fig = Figure(resolution = (1200, 1200))
ax = LScene(fig[1, 1])
for i in range(-1, 1, length = 400)
    heatmap!(ax, range(-1, 1, length = 100), range(-1, 1, length = 100), rand(100,100);
        transformation = (:yz, i), transparency = true, shading = false)
end
fig
```

**Comment by ffreyer** [comment]
I get this effect with a black region rather than overexposure. That seems to be caused by a bad `near` value. 

Does this result in overexposure for you?
```julia
fig = Figure(resolution = (1200, 1200))
ax = LScene(fig[1, 1], scenekw = (clear = true, backgroundcolor = :black))
for i in range(-1, 1, length = 400)
    heatmap!(ax, range(-1, 1, length = 100), range(-1, 1, length = 100), rand(100,100);
        transformation = (:yz, i), transparency = true, shading = false)
end
ax.scene.camera_controls.near[] = 2.77
update_cam!(ax.scene, ax.scene.camera_controls)
fig
```

**Comment by lazarusA** [comment]
Yes. `clear = false or true` and `backgroundcolor = :black or :white` don't make a difference if 
```julia
ax.scene.camera_controls.near[] = 2.77
update_cam!(ax.scene, ax.scene.camera_controls)
```
is present. Using your code above gives me this output (similar also if the background is white):

![Screenshot 2021-12-10 at 08 12 00](https://user-images.githubusercontent.com/19525261/145532625-b4207f2c-e0d7-4657-ba1c-1ff400cdcf9b.png)

**Comment by SimonDanisch** [comment]
Is oit enabled for the volume? Maybe it shouldn't because it already calculates the transparency correctly, so oit may brighten things incorrectly?

**Comment by ffreyer** [comment]
This is a problem the [paper](https://jcgt.org/published/0002/02/09/) also talks about:

> Without the range clamping in these functions, underflow will result in overly-
dark areas where α is small and |z| is large. Overflow will result in infinity (which
renders as black on most GPUs) where |z| is small. The maximum finite 16-bit floating
point number is 6.55 × 104, so even with the clamping, these will saturate after about
20 layers close to the camera and during compositing the accumulated weight result
should be clamped as shown in listing 3.

I didn't clamp, I just did a `max(weight, 0.00001)`. But that isn't the problem here - with the suggested `clamp(weight, 1e-4, 5e4)` I get:
![Screenshot from 2021-12-10 10-56-51](https://user-images.githubusercontent.com/10947937/145555397-d7f075fa-d4ac-4bed-8d10-cfd1e9b07b35.png)

Here's what I think is happening. We have two two things that get summed for OIT, weights and rgb colors that are multiplied by their respective weights. The r, g, b values appearing in the color sum are always smaller or equal to the weights, so the weight sum will reach infinity first. With just `max` that happens at some point and the gpu does whatever it thinks is right for `x / Inf`. I guess in my case the result is 0, and in yours it's `x / max_float`.
With clamping the divisor will also hit some maximum and after that the color values keep increasing linearly, so things go towards white. The next value that will hit infinity is the green part of color. My gpu sets that to 0 and I'm left with red + blue = violet. Then blue disappears and then finally red.

So this is a result of floats becoming infinite/overflowing which is caused by having many transparent objects and having them close to the minimum depth, i.e. the near plane. 

There are two ways to fix this:
1. Reduce the importance of depth in the weight function. Currently the function is `color.a * max(0.01, 3000 * pow((1 - gl_FragCoord.z), 3))`. Reducing the `3000` to about `500` does the trick, but that should also mean that two close-in-depth planes will look less ordered. Maybe we can add a uniform to adjust the factor?
2. Adjust the clipping planes so we don't get extreme depth values

(And "plot less transparent stuff stacking on top of each" but that's not a great solution.)
