### ISSUE TITLE
Call `show_data` for nested Combined/recipe plots

### ISSUE THREAD

**Issue by fbanning** [JuliaPlots/Makie.jl#1520]
What's the correct approach to call the `show_data` function for a combined plot that's nested inside another recipe plot?
I've tried the following:

```julia
# assume that ParentPlot is a recipe that creates one plot of the type NestedPlot
# which itself is just a recipe for a primitive scatter plot

function show_data(inspector::DataInspector, pp::ParentPlot, idx, np::NestedPlot)
    return Makie.show_data(inspector, np, idx)
end

function show_data(inspector::DataInspector, plot::NestedPlot, idx, ::Scatter)
    # actual show_data functionality for the scatter plot
    return true
end
```

How can I achieve what I'm trying to do?

**Comment by ffreyer** [comment]
Let's say your plot structure is
```
ParentPlot
> NestedPlot
   > PrimitivePlot
```
Makie's `pick` methods can only find primitive plots like scatter, lines etc. (All the ones in MakieCore.) So DataInspector triggers off of some `PrimitivePlot` but it moves up the tree completely before trying to call `show_data`. So it goes

1. `show_data(inspector, ::ParentPlot, primitive_idx, ::PrimitivePlot)`
2. `show_data(inspector, ::NestedPlot, primitive_idx, ::PrimitivePlot)`
3. `show_data(inspector, ::PrimitivePlot, primitive_idx)`

continuing to the next step if `show_data` from the previous step returns false and stopping if it returns true. The second plot passed is always the primitive plot because that's the context for the given index.

You only need to worry about `ParentPlot` if that should do something different from `NestedPlot` (or `PrimitivePlot` if `NestedPlot` has no `show_data` method). So you probably just need to implement the second function you listed.

**Comment by fbanning** [comment]
Thank you very much for the explanation, @ffreyer. My thinking was that Makie goes from "top to bottom" but as you pointed out, it goes recursively from "bottom to top". Got it working now. :)
