### ISSUE TITLE
Record function does not record

### ISSUE THREAD

**Issue by sdall** [JuliaPlots/Makie.jl#1539]
I observed that the example taken from your docs only repeats the first frame. However, I expected to see an animation. 
The call produced a gif in which the first frame was repeated 255 times. I noticed the same behaviour, while I was recording changes in a heatmap. 

```julia
fig, ax, p = lines(rand(10))
record(fig, "test.gif") do io
    for i in 1:255
        p[:color] = RGBf(i/255, (255 - i)/255, 0) # animate figure
        recordframe!(io)
    end
end
```
If this is due to Tier 3 support of the M1 platform, please feel free to ignore this issue. 

Thank you!

GLMakie v0.4.7
julia version 1.7.1
Big Sur 12.1 (M1)

**Comment by RomeoV** [comment]
Where in the docs did you find this? If you add an extra bracket as described [here](https://makie.juliaplots.org/v0.15.2/documentation/nodes/index.html), i.e. you write
```
        p[:color][] = RGBf(i/255, (255 - i)/255, 0) # animate figure
```
the example works fine.

**Comment by SimonDanisch** [comment]
>If you add an extra bracket as described

You don't need the brackets (`setindex!` and `setproperty!` are overloaded to update the observable), and I'd recommend using `p.color = ...`.
This example works like expected on my pc...I find it hard to believe that this is an M1 issue, but I guess it's the only thing that is different here...Pretty sure its also not a wrong version, since this syntax hasn't been changed in forever.
