### ISSUE TITLE
Turn off frame box

### ISSUE THREAD

**Issue by grero** [JuliaPlots/Makie.jl#158]
Is there currently a way to turn off the box around the axis? The ability to individually turn of these "spines" as they are called in matplotlib is something I use all the time in my current PyPlot drawing code in order to make the plots look nicer. It would be great if I could also do this in Makie.

**Comment by mkborregaard** [comment]
Alternatively a "framestyle" argument with options, eg. :box, :semi, :axes, :origin, :zerolines, :grid, :none .
That's just a different strategy than specifying each on individual axes.

**Comment by SimonDanisch** [comment]
you can do:
```Julia
 scatter(rand(10), rand(10), axis = (frame = (linewidth = 0,),))
```
(Note, current tagged version doesn't work with NamedTuples, so you'll need to use `NT(frame = ...)`
I should add some magic for this :)

**Comment by dgleich** [comment]
Just wanted to drop a comment here as setting linewidth=0 doesn't seem to work on the most recent version of Makie (and this issue shows up in the google search... so this is really putting the info to where  Google returns it rather than contributing to the issue...) 

On recent versions of Makie, I used the following code to get an empty frame box. 

```
empty_theme = Theme(
    Axis = (
        backgroundcolor = :transparent,
        leftspinevisible = false,
        rightspinevisible = false,
        bottomspinevisible = false,
        topspinevisible = false,
        xticklabelsvisible = false, 
        yticklabelsvisible = false,
        xgridcolor = :transparent,
        ygridcolor = :transparent,
        xminorticksvisible = false,
        yminorticksvisible = false,
        xticksvisible = false,
        yticksvisible = false,
        xautolimitmargin = (0.0,0.0),
        yautolimitmargin = (0.0,0.0),
    )
)
fig = with_theme(empty_theme) do
       lines(cumsum(randn(1000)))
       end
```

Note that this currently leaves a small border around the interior of the plot when saved/displayed. (There may be an option in the theme to set this...

If you want absolutely no border, then either of the two following choices work...

Choice 1
```
fig = with_theme(empty_theme) do
       lines(cumsum(randn(1000)))
       end
fig.axis.scene 
```

Choice 2
```
fig = lines(cumsum(randn(1000)))
tightlimits!(fig.axis)
fig.axis.scene  
```

**Comment by karlwessel** [comment]
> fig.axis.scene

Thank you! I was getting crazy trying to get rid of the margins of a plot without axis decorations!
