### ISSUE TITLE
Event system documentation and usability

### ISSUE THREAD

**Issue by ffreyer** [JuliaPlots/Makie.jl#1611]
It would be good to add a tutorial on how to use events. Perhaps a small game like Minsweeper? The general documentation could also be more extensive.

With respect to usability there are a bunch of functions that kind of got left behind when figures (and MakieLayout in general) were introduced. Lots of functions don't work with Figure, Axis, Axis3 and/or LScene, so you end up writing `ax.scene` and `fig.scene` frequently.

Some function aren't currently exported but probably should be. For example `is_mouseinside`.

Some functions could be simplified, e.g `pick(scene, pos)` is usually called with the current mouse position so why not make that the default?

**Comment by jkrumbiegel** [comment]
So one of the reasons I made the separate system for Axis was that I wanted it to be easy to enable/disable interactions because I imagined that for any slightly more complex app, you'd want to be able to do that. However, if one just directly hooks into the low level observables, it becomes hard to have such modularity, the user has to do all housekeeping. While working towards a more general solution, I'd like it if we'd keep that aspect in mind.
