### ISSUE TITLE
heatmap permutes data

### ISSUE THREAD

**Issue by anandijain** [JuliaPlots/Makie.jl#1791]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/33790004/160934673-2ec90728-3090-4e10-8a03-098061ca4ca7.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/33790004/160934821-d63857c6-67b7-4e70-81c5-89f38a303906.png">

**Comment by JonasIsensee** [comment]
While this may not be what you were expecting, this is correct behaviour.
matrix columns are shown along the X axis and rows along Y. (so that you can think of "indexing" as matrix[x,y,z])
Then also note that one prints matrices with mat[1,1] in the top left corner while the point (0,0) of a heatmap is in the lower left.
