### ISSUE TITLE
Maintaining the same aspect ration when changing window size

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#180]
Hello,

I have a hard time finding the right attribute how to set the aspect ratio of the plot and have it retain the same aspect ratio upon changing the window size. I am digging through the documents and forum but nothing pops up so far.

Best,

**Comment by SimonDanisch** [comment]
Currently, there is only don't change aspect ratio (scale_plot = false) and scale to window aspect ratio (scale_plot = true)... Do you actually want to define a different aspect ratio and have that independent from the parent window?
What you could do is to create a subscene with a fixed resolution:
```Julia
using Makie
scene = Scene(resolution = (1000, 1000))
sub = Scene(scene, IRect(0, 0, 500, 1000))
scatter!(sub, rand(10), rand(10))
display(scene)
```
Currently that makes the enclosing scene black, because it doesn't contain anything to render - I guess that should be considered as a bug... you could just render something invisible like:
```julia
using Makie
scene = Scene(resolution = (1000, 1000))
sub = Scene(scene, IRect(0, 0, 500, 1000))
scatter!(sub, rand(10), rand(10))
lines!(scene, rand(4), rand(4), raw = true, linewidth = 0)
scene
```

**Comment by wsrinin** [comment]
Thank you very much for the second solutions. You are right that I want to define a different aspect ratio (or rather have it fix) and have that independent from the parent window.
