### ISSUE TITLE
Bad display (scaling) for `surface`.

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#185]
MWE:

```julia
using Makie
x = y = range(-10, 10, length = 30)
function xy_data(x, y)
           r = sqrt(x^2 + y^2)
           r == 0.0 ? 1f0 : (sin(r)/r)
end

surface(x, y, z)
```
makes with full default settings

![image](https://user-images.githubusercontent.com/19669089/47498254-06a78480-d85d-11e8-99c3-6f0ed7a15e6a.png)

Two problems:
1. The 3D plot should span as much as possible the opened figure (75% whitespace isn't really helpful).
2. There should be some better scaling across the axis. I assume this uses real data scaling, but this is not optimal. The z axis should be automatically scaled so that it has same plotted size as x, y, regardless of the actual data numbers. If I really need exact data scaling instead of visual scaling, I should have an option to do it, but the default should have equal visual scaling instead of data scaling.

**Comment by SimonDanisch** [comment]
I simply skip scaling for 3D, because I wasn't really sure what a good default would be!
but in theory, it's as easy as:
```Julia
s = surface(rand(100 , 100))
scale!(s, 1/100, 1/100, 1)
update_cam!(s, FRect3D(Vec3f0(0), Vec3f0(1)))
```
![image](https://user-images.githubusercontent.com/1010467/47500582-7a4c9000-d863-11e8-9578-3ec1db1bda92.png)

This immediately unconvered two bugs :D first, axis doesn't respect scaling for axis labels yet (that's why they overlap), and the boundingbox seems wrong, which is why `center!(scene)` doesn't work

**Comment by asinghvi17** [comment]
`scale_plot` should help with this, I think.
