### ISSUE TITLE
Can't use latex z-labels with 3D surface plot

### ISSUE THREAD

**Issue by DanielVandH** [JuliaPlots/Makie.jl#1866]
A plot created using `surface` is completely emptied when a $z$-label with latex formatting is used. For example, the following works:
```
using CairoMakie
x = collect(-2:0.01:2) 
y = collect(-2:0.01:2)
Z = [1/(1+(x+im*y)^2) for x in x, y in y]
fig = Figure()
ax = Axis3(fig[1, 1], zlabel = "|1/(1+z^2)|")
surface!(ax, x, y, abs.(Z))
zlims!(ax, 0, 5)
```
But the following produces an empty axis, despite calling `surface!` after the `Axis3` call:
```
x = collect(-2:0.01:2) 
y = collect(-2:0.01:2)
Z = [1/(1+(x+im*y)^2) for x in x, y in y]
fig = Figure()
ax = Axis3(fig[1, 1], zlabel = L"|1/(1+z^2)|")
surface!(ax, x, y, abs.(Z))
zlims!(ax, 0, 5)
```

**Comment by asinghvi17** [comment]
Could you post your current versions (output of `]st -m Makie CairoMakie MathTeXEngine`) and OS?  I can't replicate this on master.

**Comment by stelmo** [comment]
This is similar to #1492

**Comment by DanielVandH** [comment]
> Could you post your current versions (output of `]st -m Makie CairoMakie MathTeXEngine`) and OS? I can't replicate this on master.

Windows 10
```
(@v1.7) pkg> st -m Makie CairoMakie MathTeXEngine
      Status `C:\Users\licer\.julia\environments\v1.7\Manifest.toml`
  [13f3f980] CairoMakie v0.7.5
  [ee78f7c6] Makie v0.16.6
  [0a4f8689] MathTeXEngine v0.2.1
```

**Comment by asinghvi17** [comment]
I can replicate this behaviour with those versions, but not on master.  It is most likely that some fix introduced after Makie v0.16.6 fixes this issue.  With GLMakie's latest tagged version, the z-label does not display, but the surface is still displayed.


With LaTeXString (CairoMakie):
<img src="https://user-images.githubusercontent.com/32143268/166399913-d23bfcad-161b-41cc-b31a-053c6191735e.png" width=468></img>
With normal string (CairoMakie):
<img src="https://user-images.githubusercontent.com/32143268/166400015-57dcab96-6ad7-4ba8-80b3-34f19d086d36.png" width=468></img>
With LaTeXString (GLMakie):

<img width="468" alt="Screen Shot 2022-05-02 at 11 06 00 PM" src="https://user-images.githubusercontent.com/32143268/166400254-649fc321-15ef-4479-b92f-b878ba28c0a3.png">

**However**, on current master,

GLMakie:
<img width="512" alt="Screen Shot 2022-05-02 at 11 08 36 PM" src="https://user-images.githubusercontent.com/32143268/166400388-3630430b-4e7a-4b80-a30c-2bdb9adb49ac.png">


CairoMakie:
<img src="https://user-images.githubusercontent.com/32143268/166400348-d910dc1c-6fdf-4e36-8ae9-0f959b3cb628.png" width=468></img>
(note that I turned shading off here due to defaults)


By the way, @DanielVandH, it seems like the white lines in the two peaks of the figure should not be there, can you confirm that?

**Comment by DanielVandH** [comment]
@asinghvi17 I tried using `]add Makie#master` and using my same code, and I still get the same issue. Similarly if I did `add CairoMakie#master`. Is that the incorrect way to update to this branch? I also did `]update Makie` initially.  

Currently I'm looking at this:
```
(@v1.7) pkg> st Makie
      Status `C:\Users\licer\.julia\environments\v1.7\Project.toml`
  [ee78f7c6] Makie v0.16.6 `https://github.com/JuliaPlots/Makie.jl.git#master`
```
Not sure what's wrong. Apologies if this is a simple mistake I'm making here with updating. (And I will check those white lines once I've updated.)

**Comment by ffreyer** [comment]
Might have been fixed by #1754 

If you want to add Makie master you generally need MakieCore, Makie and a backend (GLMakie, CairoMakie, ...) to be on a master branch.

The line might be some anti-aliasing thing? I remember that being an issue with heatmaps.

**Comment by DanielVandH** [comment]
Thank you @ffreyer, it worked after putting those packages also on a master branch. 

@asinghvi17 In response to your question, those white lines are present on my version.

**Comment by asinghvi17** [comment]
Yeah, @ffreyer is correct here, it is most likely an antialiasing thing.  With #1872, setting `rasterize=10`, I see a thinner line:
![iTerm2 KN2ndB](https://user-images.githubusercontent.com/32143268/166518085-01924e9c-1555-4a19-85d3-12e07cb22f8c.png)
(also, the size goes down tremendously, so you may want to try this out when it merges)
This is probably worth a new issue, so I'll open one shortly.

**Comment by asinghvi17** [comment]
Closing this issue, since it seems to be fixed on current master.
