### ISSUE TITLE
Makie docs search engine yields nothing

### ISSUE THREAD

**Issue by ederag** [JuliaPlots/Makie.jl#1965]
Although the term is used in [activating backends](https://makie.juliaplots.org/stable/documentation/backends/#activating_backends),
[Searching for "activate"](https://makie.juliaplots.org/stable/search/index.html?q=activate) in the Makie docs yields nothing:
![Screenshot_20220522_093509](https://user-images.githubusercontent.com/10962809/169684240-09b644f6-4d16-45fb-a6c0-df82a4b204fb.png)
*Edit: actually, search is broken here, no result, whatever the term (tested with either firefox or konqueror)*
Nice docs, by the way !

**Comment by fatteneder** [comment]
Related #1971

**Comment by jkrumbiegel** [comment]
The lunr build crashes due to an out of memory error. The question is if that is a systemic issue, if the build can be run with more memory on GHA or if we need to find a while different search solution.

**Comment by ederag** [comment]
Searching about lunr and memory issues,
https://github.com/lucaong/minisearch was mentioned in
https://github.com/olivernn/lunr.js/issues/284#issuecomment-427222175
> MiniSearch is a tiny but powerful in-memory fulltext search engine written in JavaScript. It is respectful of resources

*Just sharing little information; I have zero knowledge about these things.*

**Comment by jkrumbiegel** [comment]
I almost have stork search running in a PR. This is a different static site search engine that has some benefits over lunr, mostly that it shows excerpts to understand the context in which the search term appears better.

However it currently doesn't completely work, the links to the results don't have the correct prefix. So far the website build only uses relative links which is nice, but that doesn't work for search because the links need to be the same no matter from what site you search. So I need to figure out how to get the prefix, and that will reintroduce the problem that clicking on a link in `stable` will change the URL to `v0.17.3` or whatever the underlying version is, which is not so good for copying and pasting links. Maybe we then also need to copy the Javascript that documenter uses for this purpose, to check if the current page is stable or dev and rewrite the URL.

**Comment by jkrumbiegel** [comment]
fixed by https://github.com/JuliaPlots/Makie.jl/pull/1985
