### ISSUE TITLE
Unexpected behavior of colormaps (cgrad)

### ISSUE THREAD

**Issue by tobydriscoll** [JuliaPlots/Makie.jl#1977]
This code:

```julia
sing CairoMakie

cmap = cgrad([:black,:white,:orange],[0,0.2,1])
f = Figure(resolution=(400,200))
ax = Axis(f[1,1])
x = range(0,1,50)
scatter!(f[1,1],Point2.(x,fill(0.,50)),color=x,colormap=cmap)
hidedecorations!(ax)
Colorbar(f[2,1],vertical=false,colormap=cmap)
```

creates this image: ![temp1](https://user-images.githubusercontent.com/3577518/170273838-c1ae2142-fd0f-4773-8f2c-a14507bdac4b.png)

The Colorbar is rendered as expected, but the points are not. The behavior I expected was what you get from calling

```julia
scatter!(f[1,1],Point2.(x,fill(0.,50)),color=get(cmap,x))
```

**Comment by asinghvi17** [comment]
I believe the problem is here:
https://github.com/JuliaPlots/Makie.jl/blob/f0ad0326f777ca36023a3f15c7b9bae138434c94/src/conversions.jl#L1102

basically, the `values` field of `cgrad` is not taken into account at all.  

This seems to have been caused by 

https://github.com/JuliaPlots/Makie.jl/pull/1723/files#diff-319f6895319eb78578eb8091872ce5a2188ab92504cc10cc987b34978bf1a8dbL1095

and I just opened a PR to fix it.
