### ISSUE TITLE
difference between `pick(ax)` and `pick(fig)`

### ISSUE THREAD

**Issue by hexaeder** [JuliaPlots/Makie.jl#1978]
Hello :) Makie 0.17 deprecated `mouse_selection(ax)` in favor of `pick(ax)`. However, it seems there is a difference between `pick(ax)` and `pick(fig)`. Based on the [interaction example](https://makie.juliaplots.org/dev/documentation/events/#point_picking) in the docs here is a MWE
```julia
using GLMakie

positions = Observable(rand(Point2f, 5))

fig, ax, p = scatter(positions, markersize=50)

on(events(fig).mousebutton, priority = 2) do event
    if event.button == Mouse.left && event.action == Mouse.press
        # Delete marker
        plt, i = pick(ax)   # <- thats the culprit here
        if plt == p
            deleteat!(positions[], i)
            notify(positions)
            return Consume(true)
        end
    end
    return Consume(false)
end

fig
```
If one uses `pick(fig)` the function works as expected. If one uses `pick(ax)` one has to click right above the marker in order to delete it, it seems like there is some miscalculation between figure and axis pixel coordinate system or something like that.

xref https://github.com/JuliaPlots/GraphMakie.jl/issues/82

**Comment by ffreyer** [comment]
Oh, that's because `pick` uses `mouse_position_px` which takes the scene area into consideration, but the native point picking doesn't. It should either be `mouseposition_px(root(get_scene(x))` in those functions or `events(x).mouseposition[]`.

All the relevant function should be in https://github.com/JuliaPlots/Makie.jl/blob/master/src/interaction/interactive_api.jl if you want to make a pr.
