### ISSUE TITLE
X / Y axes swapped in heat map

### ISSUE THREAD

**Issue by jerlich** [JuliaPlots/Makie.jl#295]
```Julia
julia> Pkg.status()
    Status `~/.julia/environments/v1.1/Project.toml`
  [e2554f3b] Clp v0.6.1
  [a93c6f00] DataFrames v0.17.1
  [c91e804a] Gadfly v1.0.1
  [7073ff75] IJulia v1.17.0
  [83e8ac13] IniFile v0.5.0
  [b6b21f68] Ipopt v0.5.3
  [4076af6c] JuMP v0.18.5
  [ee78f7c6] Makie v0.9.1
  [fdba3010] MathProgBase v0.7.7
  [39abe10b] MySQL v0.7.0
  [76087f3c] NLopt v0.5.1
  [47be7bcc] ORCA v0.2.1
  [58dd65bb] Plotly v0.2.0
  [f0f68f2c] PlotlyJS v0.12.3
  [91a5bcdd] Plots v0.23.0
  [612083be] Queryverse v0.2.0
  [ee283ea6] Rebugger v0.2.2
  [2913bbd2] StatsBase v0.27.0

using Makie
result = let
              data = rand(6,100)
              scence = heatmap(data)
              end
```
<img width="484" alt="screen shot 2019-02-22 at 10 12 00 pm" src="https://user-images.githubusercontent.com/2465395/53247658-e4c8ec00-36ee-11e9-8826-4e79763f8d91.png">

The x axis only has 6 elements but goes 1:100, the y-axis has 100 elements but ticks go 1:6.

**Comment by mkborregaard** [comment]
Dup of https://github.com/JuliaPlots/Makie.jl/issues/205 , see the discussion there.

**Comment by ssfrr** [comment]
I don't think this is a duplicate. It's a real issue that was reported in #205 ([here](https://github.com/JuliaPlots/Makie.jl/issues/205#issuecomment-435183668), [here](https://github.com/JuliaPlots/Makie.jl/issues/205#issuecomment-441498026), and [here](https://github.com/JuliaPlots/Makie.jl/issues/205#issuecomment-442165930)) but somewhat buried within the larger discussion of whether heatmaps should be displayed transposed or not. It's not a question of whether the whole plot should be transposed or not, but that the data and the axes need to be consistent.

I think that @tshort has suggested a reasonable fix.

If the behavior in this issue is still present in `master` than I'd propose to keep this issue open.

**Comment by ianshmean** [comment]
I'm keen to use Makie for an application with mixed plotting of images & shapes, so it would be great to get the axes size bug fixed, and options exposed to make `image` use default to standard image orientation (transposed & y-flipped), with exposed kwargs... So I created a PR: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/98
