### ISSUE TITLE
blank plot with axis-aligned camera

### ISSUE THREAD

**Issue by colinxs** [JuliaPlots/Makie.jl#445]
```julia
sc = scatter(rand(10, 3))
cam3d!(sc,
    eyeposition = [0, 0, -1],
    lookat = [0, 0, 1]
)
display(sc)
```
yields a blank scene. Changing the x or y components of either `eyeposition` or `lookat` by some small amount works, however:
```julia
sc = scatter(rand(10, 3))
cam3d!(sc,
    eyeposition = [0, 0.0000001, -1],
    lookat = [0, 0, 1]
)
display(sc)
```

This is with Makie@v0.9.5 and AbstractPlotting@v0.9.26

**Comment by ffreyer** [comment]
This probably happens because your up direction (default `[0, 0, 1]`) is parallel to `eyeposition - lookat`. In that case the camera coordinate system cannot be specified and rendering will fail.

You *should* be able to fix this by supplying an `upvector`, but that doesn't really work for me. Neither does directly updating via `sc.camera_controls[].upvector[] = Vec3f0(0, 1, 0)`.

Doing
```julia
cam = cam3d!(sc, eyeposition=[0, 0, 1], lookat=[0, 0, -1], upvector=[0, 1, 0])
update_cam!(sc, cam)
```
works if you don't update the scene in any other way afterwards (i.e. no mouse drag, no `display(sc)` etc)

I reckon something is recalculating these vectors incorrectly or is resetting `upvector = Vec3f0(0, 0, 1)`. Both `eyeposition` and `upvector` become `[NaN, NaN, NaN]` after an update. This line seems suspicious to me, but I don't think it's actually getting called.

https://github.com/JuliaPlots/AbstractPlotting.jl/blob/e97c641b12ab8e86db31c871a93ac10d85e08955/src/camera/camera3d.jl#L295
