### ISSUE TITLE
Zooming rotates the view as well

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaPlots/Makie.jl#601]
It seems that if one resizes the window and then uses zooming the scene might rotate as well. Here is a gif showing what happens: 

![Peek 2020-05-12 22-18](https://user-images.githubusercontent.com/8392709/81746770-ebcc4d80-949e-11ea-8113-a74019281203.gif)

Test script:
```julia
using GeometryBasics
using MakieGallery
using AbstractPlotting

cat = MakieGallery.loadasset("cat.obj")
vertices = decompose(Point3f0, cat)
faces = decompose(TriangleFace{Int}, cat)
coordinates = [vertices[i][j] for i = 1:length(vertices), j = 1:3]
connectivity = [faces[i][j] for i = 1:length(faces), j = 1:3]

scene=Scene()
mesh!(scene,coordinates, connectivity,
    color = rand(length(vertices))
)

wireframe!(scene[end][1], color = (:black, 0.6), linewidth = 3)
# cam3d_cad!(scene)

cam = cameracontrols(scene)
cam.rotationspeed[]=0.05
scene
```

**Comment by ffreyer** [comment]
It seems like 3d cameras are hard coded to have the rotation atm. This shouldn't depend on the screen size though, but rather where you're pointing while zooming.

You can create a camera that doesn't rotate with
```julia
cam_attributes = AbstractPlotting.merged_get!(:cam3d, scene, Attributes()) do
    Theme(
        rotationspeed = 0.3,
        translationspeed = 1.0,
        eyeposition = Vec3f0(3),
        lookat = Vec3f0(0),
        upvector = Vec3f0(0, 0, 1),
        fov = 45f0,
        near = 0.01f0,
        far = 100f0,
        projectiontype = AbstractPlotting.Perspective,
        pan_button = Mouse.right,
        rotate_button = Mouse.left,
        move_key = nothing
    )
end
cam = AbstractPlotting.from_dict(Camera3D, cam_attributes)
disconnect!(scene.camera)
AbstractPlotting.add_translation!(scene, cam, cam.pan_button, cam.move_key, true)
AbstractPlotting.add_rotation!(scene, cam, cam.rotate_button, cam.move_key, true)
cameracontrols!(scene, cam)
on(camera(scene), scene.px_area) do area
    update_cam!(scene, cam)
end
```

This used to be what `cam3d_turntables` did, but was changed in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/347 because of https://github.com/JuliaPlots/AbstractPlotting.jl/issues/276. I think the problem here was more specific to orthographic projection. In fact moving the eyepositon shouldn't increase or decrease the size of geometry without perspective projection in the first place. @SimonDanisch
