### ISSUE TITLE
VulkanMakie?

### ISSUE THREAD

**Issue by ChetanVardhan** [JuliaPlots/Makie.jl#700]
Any chance if we'll get a VulkanMakie? Many users are facing trouble with OpenGL as backend... Installation not working and other issues. Also, Vulcan will give a better performance and is cross-platform too.

**Comment by SimonDanisch** [comment]
Those installation errors are a very specific issue with Julia + some very specific linux + intel/amd drivers - nvidia seems to be without any issue.
I hope they'll get fixed - Before those got introduced, OpenGL support has been pretty stable.
Believe me, Vulkan will in no way make this easier, since it will likely bring many other new issues - and the llvm problem that is behind those intel/amd driver issues likely will also happen for Vulkan, since it builds upon the same tech stack for those vendors.

Regardless, a Vulkan backend is still planned, although with low priority.
I hope to switch soon to some abstractions, that will work across WebGL, OpenGL & Vulkan and at that point it should just be a matter of implementing the abstraction for Vulkan.

**Comment by ChetanVardhan** [comment]
I am using Nvidia though...
Glad to know the Vulcan backend is in your list.
Its low priority so I'm guessing it'll take a lot of time...?

**Comment by SimonDanisch** [comment]
Yeah likely... What problems did you have with nvidia?

**Comment by ChetanVardhan** [comment]
The building of GLMakie failed because it couldn't find drivers in the dri folder. There're dozens of those issues! I did resolve the issue, but the second plot made my system go slow motion. It felt like it was not using my GPU at all. I closed and reopened julia and it stopped plotting due to some issue in libGL. I did post the issues but it was closed immediately marked as duplicate
There're dozens of complains over GLMakie, either directly or mentioned, and they're the exact same complain. 
Also, when I ran ]test GLFW, it gave the same error as above, leading me to believe there's some problem with that package.

**Comment by ChetanVardhan** [comment]
Makie is an awesome production level package and it's almost in pure Julia. But it must even run to allow the users to even complete the tutorial. Whats the status on GRMakie? Will it use the GPU and will it require opengl dependencies?

**Comment by mkborregaard** [comment]
GRMakie does not use the GPU and does not require openGL. Check also CairoMakie.

**Comment by ChetanVardhan** [comment]
Does CairoMakie make use of the GPU？

**Comment by mkborregaard** [comment]
No, only GLMakie does that.

**Comment by ChetanVardhan** [comment]
Thanks for the information
Cairo is really slow.
I hope the Vulkan backend comes along soon. I'll keep installing Makie and updating GLFW from time to time, hoping for the issue of GLMakie to get resolved in one of the updates！

**Comment by mkborregaard** [comment]
You are still very vague about what the issues actually are. I have no problems with GlMakie myself.

**Comment by ChetanVardhan** [comment]
https://github.com/JuliaPlots/Makie.jl/issues/699

**Comment by ChetanVardhan** [comment]
There are many solutions as many people got this exact same problem and opened issues.
None of the solutions worked for me！
The exact same error as #699 showed up when I ran ]test GLFW too
Which led me to think if we'll get another backend which can use the GPU. For cross-platform, Vulkan was the first thing which came to my mind

**Comment by mkborregaard** [comment]
Ah OK thanks. And you upgraded your nvidia drivers?

**Comment by ChetanVardhan** [comment]
All my drivers are already up to date！
Is there something you'd like me to type into the terminal and post the result here？
Fedora 32 64-bit NVIDIA GEFORCE MX130, intel i5, intel UHD

**Comment by SimonDanisch** [comment]
Yeah, so that's not an NVIDIA problem as I pointed out - NVIDIA (almost) never made any problems as far as I'm informed...

>failed to open iris

That's exactly the _INTEL_ + Linux problem I'm talking about, and I'm 99% sure, that Vulkan will show exactly the same issue ;)

Did you try:
https://github.com/JuliaPlots/Makie.jl/issues/630#issuecomment-686742412

Btw, this is a new issue (last couple of months) coming from some Intel/AMD & Linux & Julia updates, that I can absolutely do nothing about, which is pretty annoying...

You should complain to Linux GPU support ;)

**Comment by ChetanVardhan** [comment]
I solved it by (on Fedora/GNOME)
1. Right-click on your Terminal/Editor/IDE and click on "Launch using Dedicated graphics card"
2. (in your terminal) DRI_PRIME=1 Editor/IDE 
3. (in your terminal) DRI_PRIME=1 Terminal/julia  IS A BAD IDEA
The first run wait is still a bummer.
Anyway, thanks a lot for helping! My issue is officially resolved!

**Comment by ChetanVardhan** [comment]
I solved it by (on Fedora/GNOME)
1. Right-click on your Terminal/Editor/IDE and click on "Launch using Dedicated graphics card"
2. (in your terminal) DRI_PRIME=1 Editor/IDE 
3. (in your terminal) DRI_PRIME=1 Terminal/julia  IS A BAD IDEA
The first run wait is still a bummer.
Anyway, thanks a lot for helping! My issue is officially resolved!

**Comment by ChetanVardhan** [comment]
Also, StatsMakie downgrades my Optim.jl and its dependencies heavily. 
Should I open a new issue for it? It looks like a problem with tags, if so, it could be resolved quickly...
![Screenshot from 2020-09-11 23-19-29](https://user-images.githubusercontent.com/51269425/92956924-56a98780-f485-11ea-8370-33264cf01a58.png)

**Comment by SimonDanisch** [comment]
StatsMakie is deprecated in favor of AlgebraOfGraphics.jl!

**Comment by ChetanVardhan** [comment]
Kindly update the docs then！

**Comment by ChetanVardhan** [comment]
Also, AlgebraOfGraphics.jl is a part of Makie too？

**Comment by jkrumbiegel** [comment]
No it is a separate package, as statsmakie was

**Comment by SimonDanisch** [comment]
We updated the docs, I'll check if it's already deployed!
