### ISSUE TITLE
GLMakie and hybrid Nvidia graphics in Ubuntu

### ISSUE THREAD

**Issue by Sleort** [JuliaPlots/Makie.jl#723]
### The issue

My laptop runs Ubuntu 20.04. It has a discrete Nvidia GeForce GTX 1650 Ti GPU, which is set to be used on demand ("hybrid graphics") following https://support.system76.com/articles/graphics-switch-ubuntu/ . This works great with `CuArray`s, i.e. I do not need to do anything else besides `using CUDA`, and GPU computing just works. (GL)Makie, on the other hand, fails unless I have launched Julia as
```
$ __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia julia
```
(instead of the standard `$ julia`)

Would it be possible to somehow make Makie automatically run the above command if launched, making the user experience as smooth as with `CUDA.jl`? :slightly_smiling_face: 

### Additional information that may/may not be useful
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

(@v1.5) pkg> st Makie
Status `~/.julia/environments/v1.5/Project.toml`
  [ee78f7c6] Makie v0.11.1
```
```
$ nvidia-smi
Wed Oct 14 11:05:21 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.28       Driver Version: 455.28       CUDA Version: 11.1     |
```

**Comment by SimonDanisch** [comment]
>Would it be possible to somehow make Makie automatically run the above command if launched, making the user experience as smooth as with CUDA.jl?

Well, it's a completely different problem, since from CUDA's point of view, there is only the 1650ti.

This more of an operating system UI problem, that can't really be solved by GLMakie, since the user intention is not clear.
In theory, if intel wasn't messing up the drivers, GLMakie should run very well on the integrated gpu - so it's totally reasonable, to start with that. Also, the User may decide to always prefer one GPU over the other, which can be achieved in various OS settings, which we wouldn't want to overwrite.

If anyone figures out the various commands that can be run at __runtime__ to switch between GPUs, i'd be happy to have those functions live in GLMakie... The only problem is, that it seems pretty confusing and inconsistent, how switching is done across operating systems. So not much value would be added to GLMakie, if it isn't working reliably and the user will still end up in google hell...

**Comment by Sleort** [comment]
I see... Well, thanks for the explanation!

Let's hope Intel stops "messing up the drivers", so GLMakie could run also on the integrated GPU. That would obviously be the best solution!
