### ISSUE TITLE
colorS and linesegment

### ISSUE THREAD

**Issue by edljk** [JuliaPlots/Makie.jl#76]
It seams that `linesegment` does not use multiple colors. Perhaps it is the same for other attributes..
The following code produces two red lines (no green line).

````julia
scene = Makie.Scene()
linesloc = [Point(rand(Float32, 2)...) => Point(rand(Float32, 2)...) for k = 1:2]
colloc = [Colors.RGBA{Float32}(1, 0, 0) Colors.RGBA{Float32}(0, 1, 0)]
Makie.linesegment(scene, linesloc, colors = colloc)
Makie.center!(scene)
````

**Comment by SimonDanisch** [comment]
Because you can do this:
![grafik](https://user-images.githubusercontent.com/1010467/37783271-5348f552-2df5-11e8-94a3-2851560f3611.png)
so you actually need to supply a color for each point:
```Julia
using Makie, GeometryTypes
scene = Makie.Scene()
linesloc = [rand(Point2f0) => rand(Point2f0) for k = 1:2]
colloc = [Colors.RGBA{Float32}(1, 0, 0), Colors.RGBA{Float32}(0, 0, 0), Colors.RGBA{Float32}(1, 1, 0), Colors.RGBA{Float32}(0, 1, 0)]
Makie.linesegment(scene, linesloc, color = colloc, linewidth = 20)
Makie.center!(scene)
```
Note, that it's `color` in makie, not `colors`.
Maybe, if there are only N ÷ 2 colors, we could duplicate each color to color each line segment ;)
Pr would be welcome :)

**Comment by edljk** [comment]
Ah ok, very nice feature!!
I just add three lines [here](https://github.com/JuliaPlots/Makie.jl/pull/77). Comments welcome.
