### ISSUE TITLE
bump GLMakie version in compat

### ISSUE THREAD

**Issue by j-fu** [JuliaPlots/Makie.jl#785]
Hi  don't know why it worked up to now ...  

adding Makie to a clean environment now locks GLMakie at 0.1.13. ..  but there is already 0.1.19  with the backlight...

**Comment by SimonDanisch** [comment]
Well, adding is Makie is a bit out of fashion at this points, since using the backends is exactly like `using Makie`
```julia
using GLMakie
# any plot code
```
It's not that clearly communicated yet, since I'm not 100% sure what we want to do going forward.
One idea is to just archive & deprecate `Makie.jl`, or to actually move all of AbstractPlotting into Makie.jl and remove AbstractPlotting this way ;) 
I try to still somewhat update the version bounds in Makie.jl, see, that it currently requires 0.1.18: https://github.com/JuliaPlots/Makie.jl/blob/master/Project.toml#L13
I'm not sure what's going wrong there^^

**Comment by SimonDanisch** [comment]
Ah, the tag didn't go through :D https://github.com/JuliaRegistries/General/pull/26199

**Comment by j-fu** [comment]
> Well, adding is Makie is a bit out of fashion at this points, since using the backends is exactly like `using Makie`
> 
> ```julia
> using GLMakie
> # any plot code
> ```
Ah I see. 

> It's not that clearly communicated yet, since I'm not 100% sure what we want to do going forward.
> One idea is to just archive & deprecate `Makie.jl`, or to actually move all of AbstractPlotting into Makie.jl and remove AbstractPlotting this way ;)

I think there might already quite a bit of code around with is using Makie...  May be the same approach to backend choice as Plots.jl has  could work:  `using Makie` and the calling "glmakie()" or "wglmakie()" or "cairomakie()"  together with some heuristics for choosing a reasonable default could be another option.

... my personal pattern to avoid complex dependencies is to pass the plot module to the plot function,
so I do `myplot(mygrid, myfunc, Plotter=Makie)` or `myplot(mygrid, myfunc, Plotter=PyPlot)` , so I am prepared for any choice here :)
