### ISSUE TITLE
`text!` ignores `show_axis`

### ISSUE THREAD

**Issue by mschauer** [JuliaPlots/Makie.jl#877]
```
canvas = Figure(resolution=(1500,1500))
canvas[1,1] =  ax = Axis(canvas, title = "Abc", aspect=DataAspect())
text!(ax, "CDE", textsize=2, show_axis=false)
```

**Comment by ffreyer** [comment]
`show_axis` applies to the old axis. If you want to adjust the current 2d `Axis` you need to use things like `hidedecorations!(ax)`. If you want to get rid of the axis all together you need to use `LScene(fig, scenekw=(show_axis=false, ))` instead. If you don't need the layouting stuff you could also use a `Scene(show_axis=false)` instead of a figure (and axis).

**Comment by mschauer** [comment]
Thanks, I move it as QA to discourse.
