### ISSUE TITLE
arrows hang for some inputs

### ISSUE THREAD

**Issue by Kolaru** [JuliaPlots/Makie.jl#916]
For some inputs (I don't know how specific) the `arrows` function seem to hang forever.

Below the first call to arrows works just fine, but the second never return (I waited few minutes).

```julia
using CairoMakie

arrows([1], [1], [2], [2])  # Fine and fast

u, v, x0, y0 = (-1.0116670523530047e-7, -2.0314558923928416e-8, -0.3323426634879212, -0.0008194775727616843)
arrows([x0], [y0], [u], [v])  # Never return
```

Relevant packages versions:
>  [537997a7] AbstractPlotting v0.17.2
>  [13f3f980] CairoMakie v0.4.4

**Comment by ffreyer** [comment]
An interrupt spits out:

```julia
Stacktrace:
  [1] _growbeg!
    @ ./array.jl:882 [inlined]
  [2] pushfirst!
    @ ./array.jl:1253 [inlined]
  [3] get_minor_tickvalues(i::IntervalsBetween, scale::Function, tickvalues::Vector{Float32}, vmin::Float32, vmax::Float32)
    @ AbstractPlotting.MakieLayout ~/.julia/dev/AbstractPlotting/src/makielayout/lineaxis.jl:596
  ...
```

which points to this loop in [lineaxis.jl](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/76e77c53d677cd6920efb265ac68abd9e75700d8/src/makielayout/lineaxis.jl#L595):

```julia
while v >= vmin
    pushfirst!(vals, v)
    v -= stepsize
end
```

I guess what happens is that `stepsize` becomes effectively 0.

**Comment by jkrumbiegel** [comment]
that's weird, I thought that could never happen in `identity` scaling. are the ticks just somehow unusually close together, so that dividing the range by 2 == 0?

**Comment by jkrumbiegel** [comment]
yeah it was a problem with zero stepsize, although that again is a problem with Float32. So it needs a deeper solution long term, but for now I've removed the while loop in this PR https://github.com/JuliaPlots/AbstractPlotting.jl/pull/695 and now it errors instead of hanging. I hope that in most real-world cases limits are not that tiny, but for now one would have to work around that by multiplying data with some constant I guess. I'll close this hanging issue, we can open another one for the Float32 tiny limit problem later
